#ifndef HistManager_TwoTrackHists_H
#define HistManager_TwoTrackHists_H

#include "HistManager/ManageHists.h"
#include <set>

#ifndef __MAKECINT__
#include "xAODTracking/TrackParticle.h"
#endif // not __MAKECINT__

class TwoTrackHists : public ManageHists {

 public:

  TwoTrackHists(TString name);
  ~TwoTrackHists();

  void BookHists();
#ifndef __MAKECINT__
  void FillHists(const xAOD::TrackParticle* trk, float weight) const;

#endif // not __MAKECINT__

  private:

    TString m_name;

  public:

    // can these be private as well?
    TH1F* m_TargetLayerOfInterest; //!
    TH1F* m_ClusterPatternIndex; //!

    TH1F* m_minMSOSLocalDistanceAtLayer; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY; //!
    TH1F* m_minMSOSLocalDistanceAtLayer0; //!
    TH1F* m_minMSOSLocalDistanceAtLayer1; //!
    TH1F* m_minMSOSLocalDistanceAtLayer2; //!
    TH1F* m_minMSOSLocalDistanceAtLayer3; //!
    TH1F* m_minMSOSLocalDistanceAtLayer4; //!
    TH1F* m_minMSOSLocalDistanceAtLayer5; //!
    TH1F* m_minMSOSLocalDistanceAtLayer6; //!
    TH1F* m_minMSOSLocalDistanceAtLayer7; //!
    TH1F* m_minMSOSLocalDistanceAtLayer8; //!
    TH1F* m_minMSOSLocalDistanceAtLayer9; //!
    TH1F* m_minMSOSLocalDistanceAtLayer10; //!
    TH1F* m_minMSOSLocalDistanceAtLayer11; //!
    TH1F* m_minMSOSLocalDistanceAtLayer12; //!
    TH1F* m_minMSOSLocalDistanceAtLayer13; //!
    TH1F* m_minMSOSLocalDistanceAtLayer14; //!
    TH1F* m_minMSOSLocalDistanceAtLayer15; //!
    TH1F* m_minMSOSLocalDistanceAtLayer16; //!
    TH1F* m_minMSOSLocalDistanceAtLayer17; //!
    TH1F* m_minMSOSLocalDistanceAtLayer18; //!
    TH1F* m_minMSOSLocalDistanceAtLayer19; //!
    TH1F* m_minMSOSLocalDistanceAtLayer20; //!
    TH1F* m_minMSOSLocalDistanceAtLayer21; //!
    TH1F* m_minMSOSLocalDistanceAtLayer22; //!
    TH1F* m_minMSOSLocalDistanceAtLayer23; //!
    TH1F* m_minMSOSLocalDistanceAtLayer24; //!
    TH1F* m_minMSOSLocalDistanceAtLayer25; //!
    TH1F* m_minMSOSLocalDistanceAtLayer26; //!
    TH1F* m_minMSOSLocalDistanceAtLayer27; //!
    TH1F* m_minMSOSLocalDistanceAtLayer28; //!
    TH1F* m_minMSOSLocalDistanceAtLayer29; //!
    TH1F* m_minMSOSLocalDistanceAtLayer30; //!
    TH1F* m_minMSOSLocalDistanceAtLayer31; //!
    TH1F* m_minMSOSLocalDistanceAtLayer32; //!
    TH1F* m_minMSOSLocalDistanceAtLayer33; //!
    TH1F* m_minMSOSLocalDistanceAtLayer34; //!
    TH1F* m_minMSOSLocalDistanceAtLayer35; //!
    TH1F* m_minMSOSLocalDistanceAtLayer36; //!
    TH1F* m_minMSOSLocalDistanceAtLayer37; //!
    TH1F* m_minMSOSLocalDistanceAtLayer38; //!
    TH1F* m_minMSOSLocalDistanceAtLayer39; //!
    TH1F* m_minMSOSLocalDistanceAtLayer40; //!
    TH1F* m_minMSOSLocalDistanceAtLayer41; //!
    TH1F* m_minMSOSLocalDistanceAtLayer42; //!
    TH1F* m_minMSOSLocalDistanceAtLayer43; //!
    TH1F* m_minMSOSLocalDistanceAtLayer44; //!
    TH1F* m_minMSOSLocalDistanceAtLayer45; //!
    TH1F* m_minMSOSLocalDistanceAtLayer46; //!
    TH1F* m_minMSOSLocalDistanceAtLayer47; //!
    TH1F* m_minMSOSLocalDistanceAtLayer48; //!
    TH1F* m_minMSOSLocalDistanceAtLayer49; //!
    TH1F* m_minMSOSLocalDistanceAtLayer50; //!
    TH1F* m_minMSOSLocalDistanceAtLayer51; //!
    TH1F* m_minMSOSLocalDistanceAtLayer52; //!
    TH1F* m_minMSOSLocalDistanceAtLayer53; //!
    TH1F* m_minMSOSLocalDistanceAtLayer54; //!
    TH1F* m_minMSOSLocalDistanceAtLayer55; //!
    TH1F* m_minMSOSLocalDistanceAtLayer56; //!
    TH1F* m_minMSOSLocalDistanceAtLayer57; //!
    TH1F* m_minMSOSLocalDistanceAtLayer58; //!
    TH1F* m_minMSOSLocalDistanceAtLayer59; //!
    TH1F* m_minMSOSLocalDistanceAtLayer60; //!
    TH1F* m_minMSOSLocalDistanceAtLayer61; //!
    TH1F* m_minMSOSLocalDistanceAtLayer62; //!
    TH1F* m_minMSOSLocalDistanceAtLayer63; //!
    TH1F* m_minMSOSLocalDistanceAtLayer64; //!
    TH1F* m_minMSOSLocalDistanceAtLayer65; //!
    TH1F* m_minMSOSLocalDistanceAtLayer66; //!
    TH1F* m_minMSOSLocalDistanceAtLayer67; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX0; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX1; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX2; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX3; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX4; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX5; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX6; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX7; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX8; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX9; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX10; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX11; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX12; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX13; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX14; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX15; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX16; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX17; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX18; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX19; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX20; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX21; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX22; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX23; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX24; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX25; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX26; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX27; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX28; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX29; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX30; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX31; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX32; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX33; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX34; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX35; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX36; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX37; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX38; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX39; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX40; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX41; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX42; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX43; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX44; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX45; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX46; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX47; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX48; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX49; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX50; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX51; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX52; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX53; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX54; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX55; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX56; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX57; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX58; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX59; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX60; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX61; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX62; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX63; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX64; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX65; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX66; //!
    TH1F* m_minMSOSLocalDistanceAtLayerX67; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY0; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY1; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY2; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY3; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY4; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY5; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY6; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY7; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY8; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY9; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY10; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY11; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY12; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY13; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY14; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY15; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY16; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY17; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY18; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY19; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY20; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY21; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY22; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY23; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY24; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY25; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY26; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY27; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY28; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY29; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY30; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY31; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY32; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY33; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY34; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY35; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY36; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY37; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY38; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY39; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY40; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY41; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY42; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY43; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY44; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY45; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY46; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY47; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY48; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY49; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY50; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY51; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY52; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY53; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY54; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY55; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY56; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY57; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY58; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY59; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY60; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY61; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY62; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY63; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY64; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY65; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY66; //!
    TH1F* m_minMSOSLocalDistanceAtLayerY67; //!

    TH1F* m_minClusLocalDistanceAtLayer; //!
    TH1F* m_minClusLocalDistanceAtLayerX; //!
    TH1F* m_minClusLocalDistanceAtLayerY; //!
    TH1F* m_minClusLocalDistanceAtLayer0; //!
    TH1F* m_minClusLocalDistanceAtLayer1; //!
    TH1F* m_minClusLocalDistanceAtLayer2; //!
    TH1F* m_minClusLocalDistanceAtLayer3; //!
    TH1F* m_minClusLocalDistanceAtLayer4; //!
    TH1F* m_minClusLocalDistanceAtLayer5; //!
    TH1F* m_minClusLocalDistanceAtLayer6; //!
    TH1F* m_minClusLocalDistanceAtLayer7; //!
    TH1F* m_minClusLocalDistanceAtLayer8; //!
    TH1F* m_minClusLocalDistanceAtLayer9; //!
    TH1F* m_minClusLocalDistanceAtLayer10; //!
    TH1F* m_minClusLocalDistanceAtLayer11; //!
    TH1F* m_minClusLocalDistanceAtLayer12; //!
    TH1F* m_minClusLocalDistanceAtLayer13; //!
    TH1F* m_minClusLocalDistanceAtLayer14; //!
    TH1F* m_minClusLocalDistanceAtLayer15; //!
    TH1F* m_minClusLocalDistanceAtLayer16; //!
    TH1F* m_minClusLocalDistanceAtLayer17; //!
    TH1F* m_minClusLocalDistanceAtLayer18; //!
    TH1F* m_minClusLocalDistanceAtLayer19; //!
    TH1F* m_minClusLocalDistanceAtLayer20; //!
    TH1F* m_minClusLocalDistanceAtLayer21; //!
    TH1F* m_minClusLocalDistanceAtLayer22; //!
    TH1F* m_minClusLocalDistanceAtLayer23; //!
    TH1F* m_minClusLocalDistanceAtLayer24; //!
    TH1F* m_minClusLocalDistanceAtLayer25; //!
    TH1F* m_minClusLocalDistanceAtLayer26; //!
    TH1F* m_minClusLocalDistanceAtLayer27; //!
    TH1F* m_minClusLocalDistanceAtLayer28; //!
    TH1F* m_minClusLocalDistanceAtLayer29; //!
    TH1F* m_minClusLocalDistanceAtLayer30; //!
    TH1F* m_minClusLocalDistanceAtLayer31; //!
    TH1F* m_minClusLocalDistanceAtLayer32; //!
    TH1F* m_minClusLocalDistanceAtLayer33; //!
    TH1F* m_minClusLocalDistanceAtLayer34; //!
    TH1F* m_minClusLocalDistanceAtLayer35; //!
    TH1F* m_minClusLocalDistanceAtLayer36; //!
    TH1F* m_minClusLocalDistanceAtLayer37; //!
    TH1F* m_minClusLocalDistanceAtLayer38; //!
    TH1F* m_minClusLocalDistanceAtLayer39; //!
    TH1F* m_minClusLocalDistanceAtLayer40; //!
    TH1F* m_minClusLocalDistanceAtLayer41; //!
    TH1F* m_minClusLocalDistanceAtLayer42; //!
    TH1F* m_minClusLocalDistanceAtLayer43; //!
    TH1F* m_minClusLocalDistanceAtLayer44; //!
    TH1F* m_minClusLocalDistanceAtLayer45; //!
    TH1F* m_minClusLocalDistanceAtLayer46; //!
    TH1F* m_minClusLocalDistanceAtLayer47; //!
    TH1F* m_minClusLocalDistanceAtLayer48; //!
    TH1F* m_minClusLocalDistanceAtLayer49; //!
    TH1F* m_minClusLocalDistanceAtLayer50; //!
    TH1F* m_minClusLocalDistanceAtLayer51; //!
    TH1F* m_minClusLocalDistanceAtLayer52; //!
    TH1F* m_minClusLocalDistanceAtLayer53; //!
    TH1F* m_minClusLocalDistanceAtLayer54; //!
    TH1F* m_minClusLocalDistanceAtLayer55; //!
    TH1F* m_minClusLocalDistanceAtLayer56; //!
    TH1F* m_minClusLocalDistanceAtLayer57; //!
    TH1F* m_minClusLocalDistanceAtLayer58; //!
    TH1F* m_minClusLocalDistanceAtLayer59; //!
    TH1F* m_minClusLocalDistanceAtLayer60; //!
    TH1F* m_minClusLocalDistanceAtLayer61; //!
    TH1F* m_minClusLocalDistanceAtLayer62; //!
    TH1F* m_minClusLocalDistanceAtLayer63; //!
    TH1F* m_minClusLocalDistanceAtLayer64; //!
    TH1F* m_minClusLocalDistanceAtLayer65; //!
    TH1F* m_minClusLocalDistanceAtLayer66; //!
    TH1F* m_minClusLocalDistanceAtLayer67; //!

    TH1F* m_minClusGlobalDistanceAtLayer; //!
    TH1F* m_minClusGlobalDistanceAtLayerX; //!
    TH1F* m_minClusGlobalDistanceAtLayerY; //!
    TH1F* m_minClusGlobalDistanceAtLayer0; //!
    TH1F* m_minClusGlobalDistanceAtLayer1; //!
    TH1F* m_minClusGlobalDistanceAtLayer2; //!
    TH1F* m_minClusGlobalDistanceAtLayer3; //!
    TH1F* m_minClusGlobalDistanceAtLayer4; //!
    TH1F* m_minClusGlobalDistanceAtLayer5; //!
    TH1F* m_minClusGlobalDistanceAtLayer6; //!
    TH1F* m_minClusGlobalDistanceAtLayer7; //!
    TH1F* m_minClusGlobalDistanceAtLayer8; //!
    TH1F* m_minClusGlobalDistanceAtLayer9; //!
    TH1F* m_minClusGlobalDistanceAtLayer10; //!
    TH1F* m_minClusGlobalDistanceAtLayer11; //!
    TH1F* m_minClusGlobalDistanceAtLayer12; //!
    TH1F* m_minClusGlobalDistanceAtLayer13; //!
    TH1F* m_minClusGlobalDistanceAtLayer14; //!
    TH1F* m_minClusGlobalDistanceAtLayer15; //!
    TH1F* m_minClusGlobalDistanceAtLayer16; //!
    TH1F* m_minClusGlobalDistanceAtLayer17; //!
    TH1F* m_minClusGlobalDistanceAtLayer18; //!
    TH1F* m_minClusGlobalDistanceAtLayer19; //!
    TH1F* m_minClusGlobalDistanceAtLayer20; //!
    TH1F* m_minClusGlobalDistanceAtLayer21; //!
    TH1F* m_minClusGlobalDistanceAtLayer22; //!
    TH1F* m_minClusGlobalDistanceAtLayer23; //!
    TH1F* m_minClusGlobalDistanceAtLayer24; //!
    TH1F* m_minClusGlobalDistanceAtLayer25; //!
    TH1F* m_minClusGlobalDistanceAtLayer26; //!
    TH1F* m_minClusGlobalDistanceAtLayer27; //!
    TH1F* m_minClusGlobalDistanceAtLayer28; //!
    TH1F* m_minClusGlobalDistanceAtLayer29; //!
    TH1F* m_minClusGlobalDistanceAtLayer30; //!
    TH1F* m_minClusGlobalDistanceAtLayer31; //!
    TH1F* m_minClusGlobalDistanceAtLayer32; //!
    TH1F* m_minClusGlobalDistanceAtLayer33; //!
    TH1F* m_minClusGlobalDistanceAtLayer34; //!
    TH1F* m_minClusGlobalDistanceAtLayer35; //!
    TH1F* m_minClusGlobalDistanceAtLayer36; //!
    TH1F* m_minClusGlobalDistanceAtLayer37; //!
    TH1F* m_minClusGlobalDistanceAtLayer38; //!
    TH1F* m_minClusGlobalDistanceAtLayer39; //!
    TH1F* m_minClusGlobalDistanceAtLayer40; //!
    TH1F* m_minClusGlobalDistanceAtLayer41; //!
    TH1F* m_minClusGlobalDistanceAtLayer42; //!
    TH1F* m_minClusGlobalDistanceAtLayer43; //!
    TH1F* m_minClusGlobalDistanceAtLayer44; //!
    TH1F* m_minClusGlobalDistanceAtLayer45; //!
    TH1F* m_minClusGlobalDistanceAtLayer46; //!
    TH1F* m_minClusGlobalDistanceAtLayer47; //!
    TH1F* m_minClusGlobalDistanceAtLayer48; //!
    TH1F* m_minClusGlobalDistanceAtLayer49; //!
    TH1F* m_minClusGlobalDistanceAtLayer50; //!
    TH1F* m_minClusGlobalDistanceAtLayer51; //!
    TH1F* m_minClusGlobalDistanceAtLayer52; //!
    TH1F* m_minClusGlobalDistanceAtLayer53; //!
    TH1F* m_minClusGlobalDistanceAtLayer54; //!
    TH1F* m_minClusGlobalDistanceAtLayer55; //!
    TH1F* m_minClusGlobalDistanceAtLayer56; //!
    TH1F* m_minClusGlobalDistanceAtLayer57; //!
    TH1F* m_minClusGlobalDistanceAtLayer58; //!
    TH1F* m_minClusGlobalDistanceAtLayer59; //!
    TH1F* m_minClusGlobalDistanceAtLayer60; //!
    TH1F* m_minClusGlobalDistanceAtLayer61; //!
    TH1F* m_minClusGlobalDistanceAtLayer62; //!
    TH1F* m_minClusGlobalDistanceAtLayer63; //!
    TH1F* m_minClusGlobalDistanceAtLayer64; //!
    TH1F* m_minClusGlobalDistanceAtLayer65; //!
    TH1F* m_minClusGlobalDistanceAtLayer66; //!
    TH1F* m_minClusGlobalDistanceAtLayer67; //!

    TH1F* m_pixLocal_shiftX; //!
    TH1F* m_pixLocal_shiftY; //!

    TH2F* m_PixelLayout_xy; //!
    TH2F* m_PixelLayout_zr; //!
    TH2F* m_PixelLayout2Hits_xy; //!
    TH2F* m_PixelLayout2Hits_zr; //!
    TH2F* m_PixelLayoutZoom_xy; //!
    TH2F* m_PixelLayoutZoom_zr; //!
    TH2F* m_PixelLayout2HitsZoom_xy; //!
    TH2F* m_PixelLayout2HitsZoom_zr; //!

    TH2F* m_etaWeight; //!
    TH2F* m_ptWeight; //!

    TH1F* m_mindRJet1; //!
    TH1F* m_mindRJet1P0; //!
    TH1F* m_mindRJet1P1; //!
    TH1F* m_mindRJet1P2; //!
    TH1F* m_mindRJet1P3; //!
    TH1F* m_mindRJet1P4; //!
    TH1F* m_mindRJet1P5; //!
    TH1F* m_mindRJet1P6; //!
    TH1F* m_mindRJet1P7; //!
    TH1F* m_mindRJet1P8; //!
    TH1F* m_mindRJet1P9; //!
    TH1F* m_mindRJet1P10; //!
    TH1F* m_mindRJet1P11; //!
    TH1F* m_mindRJet1P12; //!
    TH1F* m_mindRJet1P13; //!
    TH1F* m_mindRJet1P14; //!
    TH1F* m_mindRJet1P15; //!
    TH1F* m_mindRJet1P16; //!
    TH1F* m_mindRJet1P17; //!
    TH1F* m_mindRJet1P18; //!
    TH1F* m_mindRJet1P19; //!
    TH1F* m_mindRJet1P20; //!
    TH1F* m_mindRJet1P21; //!
    TH1F* m_mindRJet1P22; //!
    TH1F* m_mindRJet1P23; //!
    TH1F* m_mindRJet1P24; //!
    TH1F* m_mindRJet1P25; //!
    TH1F* m_mindRJet1P26; //!
    TH1F* m_mindRJet1P27; //!
    TH1F* m_mindRJet1P28; //!
    TH1F* m_mindRJet1P29; //!
    TH1F* m_mindRJet1P30; //!
    TH1F* m_mindRJet1P31; //!
    TH1F* m_mindRJet1P32; //!
    TH1F* m_mindRJet1P33; //!
    TH1F* m_mindRJet1P34; //!
    TH1F* m_mindRJet1P35; //!
    TH1F* m_mindRJet1P36; //!
    TH1F* m_mindRJet1P37; //!
    TH1F* m_mindRJet1P38; //!
    TH1F* m_mindRJet1P39; //!
    TH1F* m_mindRJet1P40; //!
    TH1F* m_mindRJet1P41; //!
    TH1F* m_mindRJet1P42; //!
    TH1F* m_mindRJet1P43; //!
    TH1F* m_mindRJet1P44; //!
    TH1F* m_mindRJet1P45; //!
    TH1F* m_mindRJet1P46; //!
    TH1F* m_mindRJet1P47; //!
    TH1F* m_mindRJet1P48; //!
    TH1F* m_mindRJet1P49; //!
    TH1F* m_mindRJet1P50; //!
    TH1F* m_mindRJet1P51; //!
    TH1F* m_mindRJet1P52; //!
    TH1F* m_mindRJet1P53; //!
    TH1F* m_mindRJet1P54; //!
    TH1F* m_mindRJet1P55; //!
    TH1F* m_mindRJet1P56; //!
    TH1F* m_mindRJet1P57; //!
    TH1F* m_mindRJet1P58; //!
    TH1F* m_mindRJet1P59; //!
    TH1F* m_mindRJet1P60; //!
    TH1F* m_mindRJet1P61; //!
    TH1F* m_mindRJet1P62; //!
    TH1F* m_mindRJet1P63; //!
    TH1F* m_mindRJet1P64; //!
    TH1F* m_mindRJet1P65; //!
    TH1F* m_mindRJet1P66; //!
    TH1F* m_mindRJet1P67; //!

    TH1F* m_mindRJet2; //!
    TH1F* m_mindRJet2P0; //!
    TH1F* m_mindRJet2P1; //!
    TH1F* m_mindRJet2P2; //!
    TH1F* m_mindRJet2P3; //!
    TH1F* m_mindRJet2P4; //!
    TH1F* m_mindRJet2P5; //!
    TH1F* m_mindRJet2P6; //!
    TH1F* m_mindRJet2P7; //!
    TH1F* m_mindRJet2P8; //!
    TH1F* m_mindRJet2P9; //!
    TH1F* m_mindRJet2P10; //!
    TH1F* m_mindRJet2P11; //!
    TH1F* m_mindRJet2P12; //!
    TH1F* m_mindRJet2P13; //!
    TH1F* m_mindRJet2P14; //!
    TH1F* m_mindRJet2P15; //!
    TH1F* m_mindRJet2P16; //!
    TH1F* m_mindRJet2P17; //!
    TH1F* m_mindRJet2P18; //!
    TH1F* m_mindRJet2P19; //!
    TH1F* m_mindRJet2P20; //!
    TH1F* m_mindRJet2P21; //!
    TH1F* m_mindRJet2P22; //!
    TH1F* m_mindRJet2P23; //!
    TH1F* m_mindRJet2P24; //!
    TH1F* m_mindRJet2P25; //!
    TH1F* m_mindRJet2P26; //!
    TH1F* m_mindRJet2P27; //!
    TH1F* m_mindRJet2P28; //!
    TH1F* m_mindRJet2P29; //!
    TH1F* m_mindRJet2P30; //!
    TH1F* m_mindRJet2P31; //!
    TH1F* m_mindRJet2P32; //!
    TH1F* m_mindRJet2P33; //!
    TH1F* m_mindRJet2P34; //!
    TH1F* m_mindRJet2P35; //!
    TH1F* m_mindRJet2P36; //!
    TH1F* m_mindRJet2P37; //!
    TH1F* m_mindRJet2P38; //!
    TH1F* m_mindRJet2P39; //!
    TH1F* m_mindRJet2P40; //!
    TH1F* m_mindRJet2P41; //!
    TH1F* m_mindRJet2P42; //!
    TH1F* m_mindRJet2P43; //!
    TH1F* m_mindRJet2P44; //!
    TH1F* m_mindRJet2P45; //!
    TH1F* m_mindRJet2P46; //!
    TH1F* m_mindRJet2P47; //!
    TH1F* m_mindRJet2P48; //!
    TH1F* m_mindRJet2P49; //!
    TH1F* m_mindRJet2P50; //!
    TH1F* m_mindRJet2P51; //!
    TH1F* m_mindRJet2P52; //!
    TH1F* m_mindRJet2P53; //!
    TH1F* m_mindRJet2P54; //!
    TH1F* m_mindRJet2P55; //!
    TH1F* m_mindRJet2P56; //!
    TH1F* m_mindRJet2P57; //!
    TH1F* m_mindRJet2P58; //!
    TH1F* m_mindRJet2P59; //!
    TH1F* m_mindRJet2P60; //!
    TH1F* m_mindRJet2P61; //!
    TH1F* m_mindRJet2P62; //!
    TH1F* m_mindRJet2P63; //!
    TH1F* m_mindRJet2P64; //!
    TH1F* m_mindRJet2P65; //!
    TH1F* m_mindRJet2P66; //!
    TH1F* m_mindRJet2P67; //!

    TH2F* m_jetpT_locT; //!
    TH2F* m_jetpT_locX; //!
    TH2F* m_jetpT_locY; //!

    TH2F* m_jetpT_locTNP; //!
    TH2F* m_jetpT_locXNP; //!
    TH2F* m_jetpT_locYNP; //!

    TH2F* m_jetpT_locTSP; //!
    TH2F* m_jetpT_locXSP; //!
    TH2F* m_jetpT_locYSP; //!

};

#endif //HistManager_TwoTrackHists_H
